### PR TITLE
Fix example program

### PR DESCRIPTION
**Pull request by chreekat**

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Oh hey it's Bryan :) Thanks 👍!

**Comment by mitchellwrosen** [comment]
Oh hey it's Bryan :) Thanks 👍!

**Comment by mitchellwrosen** [comment]
Btw, I feel compelled to mention here that if you actually try using this library, you'll find the named colors (`red`, `green`, etc.) off by one :cry:. I'm half working on fixing that, and half working on making bindings to `termbox2` instead - https://github.com/mitchellwrosen/termbox2

**Comment by chreekat** [comment]
Hey! I was thinking of using it, but it might be too low-level for me. :) I wanted to do some box-drawing stuff and I might end up using brick. But then I'm having a whale of a time actually drawing the borders I want with brick, so I don't know. 

I'm trying to create a nicer console frontend for chreekat/usort. Something that looks like this:

```
+--------------------------------------USORT--------------------------------------------------+
| Which is more important? Press 1 or 2.|                                  |Comparison 4 of ~6|
+---------------------------------------+                                  +------------------+
+---+
|[1]|
+---+-----------------------------------------------------------------------------------------+
|blah blah some stuff                                                                         |
|    multi line, why not                                                                      |
+---------------------------------------------------------------------------------------------+



+---+
|[2]|
+---+-----------------------------------------------------------------------------------------+
|Another thing lol                                                                            |
+---------------------------------------------------------------------------------------------+



-----------------------------------------------------------------------------------------------
Or: [e]dit an entry, [u]ndo last comparison, [d]elete an entry, [i]gnore an entry
-----------------------------------------------------------------------------------------------
```

What would you recommend?

**Comment by mitchellwrosen** [comment]
That's cool! I don't know, if it were me I think I'd use these termbox bindings (check out `termbox-banana` too), and build out my own little combinators for laying out a frontend like that. But that's just because I don't know of anything else between this level and going full `brick`, which I hate to say I never liked all that much.

It would be cool to look around at some other languages' terminal guis and port the good one(s) to Haskell!

**Pull request merged**
